/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as UserRouteImport } from './routes/_user'
import { Route as PartnerRouteImport } from './routes/_partner'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DTestRouteImport } from './routes/d.test'
import { Route as DShareUuidRouteImport } from './routes/d.$shareUuid'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiSuggestPurposeRouteImport } from './routes/api/suggest-purpose'
import { Route as ApiPriceCompareRouteImport } from './routes/api/price-compare'
import { Route as ApiOembedRouteImport } from './routes/api/oembed'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiConsultationsRouteImport } from './routes/api/consultations'
import { Route as ApiAbuseReportsRouteImport } from './routes/api/abuse-reports'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as UserMeRouteImport } from './routes/_user/me'
import { Route as UserInboxRouteImport } from './routes/_user/inbox'
import { Route as UserHomeRouteImport } from './routes/_user/home'
import { Route as UserExploreRouteImport } from './routes/_user/explore'
import { Route as UserCreateWizardRouteImport } from './routes/_user/create-wizard'
import { Route as UserCreateRouteImport } from './routes/_user/create'
import { Route as ApiDropsIndexRouteImport } from './routes/api/drops/index'
import { Route as ApiDiscoverIndexRouteImport } from './routes/api/discover/index'
import { Route as PartnerPartnerIndexRouteImport } from './routes/_partner/partner.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as ApiDropsShareCodeRouteImport } from './routes/api/drops/$shareCode'
import { Route as ApiCouponsClaimRouteImport } from './routes/api/coupons/claim'
import { Route as UserResultsShareUuidRouteImport } from './routes/_user/results.$shareUuid'
import { Route as UserCouponClaim_codeRouteImport } from './routes/_user/coupon.$claim_code'
import { Route as PartnerPartnerResultsRouteImport } from './routes/_partner/partner.results'
import { Route as PartnerPartnerRegisterRouteImport } from './routes/_partner/partner.register'
import { Route as PartnerPartnerRedeemRouteImport } from './routes/_partner/partner.redeem'
import { Route as PartnerPartnerCouponsRouteImport } from './routes/_partner/partner.coupons'
import { Route as PartnerPartnerCampaignsRouteImport } from './routes/_partner/partner.campaigns'
import { Route as PartnerPartnerCalendarRouteImport } from './routes/_partner/partner.calendar'
import { Route as PartnerPartnerBillingRouteImport } from './routes/_partner/partner.billing'
import { Route as AdminAdminTrendsRouteImport } from './routes/_admin/admin.trends'
import { Route as AdminAdminSourcesRouteImport } from './routes/_admin/admin.sources'
import { Route as AdminAdminRulesRouteImport } from './routes/_admin/admin.rules'
import { Route as AdminAdminExtractRouteImport } from './routes/_admin/admin.extract'
import { Route as AdminAdminDefamationRouteImport } from './routes/_admin/admin.defamation'
import { Route as AdminAdminCampaignsRouteImport } from './routes/_admin/admin.campaigns'
import { Route as PartnerPartnerCalendarDropIdRouteImport } from './routes/_partner/partner.calendar.$dropId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/_partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DTestRoute = DTestRouteImport.update({
  id: '/d/test',
  path: '/d/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DShareUuidRoute = DShareUuidRouteImport.update({
  id: '/d/$shareUuid',
  path: '/d/$shareUuid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestPurposeRoute = ApiSuggestPurposeRouteImport.update({
  id: '/api/suggest-purpose',
  path: '/api/suggest-purpose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPriceCompareRoute = ApiPriceCompareRouteImport.update({
  id: '/api/price-compare',
  path: '/api/price-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOembedRoute = ApiOembedRouteImport.update({
  id: '/api/oembed',
  path: '/api/oembed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultationsRoute = ApiConsultationsRouteImport.update({
  id: '/api/consultations',
  path: '/api/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAbuseReportsRoute = ApiAbuseReportsRouteImport.update({
  id: '/api/abuse-reports',
  path: '/api/abuse-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserMeRoute = UserMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => UserRoute,
} as any)
const UserInboxRoute = UserInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => UserRoute,
} as any)
const UserHomeRoute = UserHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => UserRoute,
} as any)
const UserExploreRoute = UserExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => UserRoute,
} as any)
const UserCreateWizardRoute = UserCreateWizardRouteImport.update({
  id: '/create-wizard',
  path: '/create-wizard',
  getParentRoute: () => UserRoute,
} as any)
const UserCreateRoute = UserCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => UserRoute,
} as any)
const ApiDropsIndexRoute = ApiDropsIndexRouteImport.update({
  id: '/api/drops/',
  path: '/api/drops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverIndexRoute = ApiDiscoverIndexRouteImport.update({
  id: '/api/discover/',
  path: '/api/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPartnerIndexRoute = PartnerPartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => PartnerRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiDropsShareCodeRoute = ApiDropsShareCodeRouteImport.update({
  id: '/api/drops/$shareCode',
  path: '/api/drops/$shareCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCouponsClaimRoute = ApiCouponsClaimRouteImport.update({
  id: '/api/coupons/claim',
  path: '/api/coupons/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const UserResultsShareUuidRoute = UserResultsShareUuidRouteImport.update({
  id: '/results/$shareUuid',
  path: '/results/$shareUuid',
  getParentRoute: () => UserRoute,
} as any)
const UserCouponClaim_codeRoute = UserCouponClaim_codeRouteImport.update({
  id: '/coupon/$claim_code',
  path: '/coupon/$claim_code',
  getParentRoute: () => UserRoute,
} as any)
const PartnerPartnerResultsRoute = PartnerPartnerResultsRouteImport.update({
  id: '/partner/results',
  path: '/partner/results',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPartnerRegisterRoute = PartnerPartnerRegisterRouteImport.update({
  id: '/partner/register',
  path: '/partner/register',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPartnerRedeemRoute = PartnerPartnerRedeemRouteImport.update({
  id: '/partner/redeem',
  path: '/partner/redeem',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPartnerCouponsRoute = PartnerPartnerCouponsRouteImport.update({
  id: '/partner/coupons',
  path: '/partner/coupons',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPartnerCampaignsRoute = PartnerPartnerCampaignsRouteImport.update({
  id: '/partner/campaigns',
  path: '/partner/campaigns',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPartnerCalendarRoute = PartnerPartnerCalendarRouteImport.update({
  id: '/partner/calendar',
  path: '/partner/calendar',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPartnerBillingRoute = PartnerPartnerBillingRouteImport.update({
  id: '/partner/billing',
  path: '/partner/billing',
  getParentRoute: () => PartnerRoute,
} as any)
const AdminAdminTrendsRoute = AdminAdminTrendsRouteImport.update({
  id: '/admin/trends',
  path: '/admin/trends',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSourcesRoute = AdminAdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRulesRoute = AdminAdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminExtractRoute = AdminAdminExtractRouteImport.update({
  id: '/admin/extract',
  path: '/admin/extract',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDefamationRoute = AdminAdminDefamationRouteImport.update({
  id: '/admin/defamation',
  path: '/admin/defamation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCampaignsRoute = AdminAdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const PartnerPartnerCalendarDropIdRoute =
  PartnerPartnerCalendarDropIdRouteImport.update({
    id: '/$dropId',
    path: '/$dropId',
    getParentRoute: () => PartnerPartnerCalendarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/create': typeof UserCreateRoute
  '/create-wizard': typeof UserCreateWizardRoute
  '/explore': typeof UserExploreRoute
  '/home': typeof UserHomeRoute
  '/inbox': typeof UserInboxRoute
  '/me': typeof UserMeRoute
  '/profile': typeof UserProfileRoute
  '/api/abuse-reports': typeof ApiAbuseReportsRoute
  '/api/consultations': typeof ApiConsultationsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/oembed': typeof ApiOembedRoute
  '/api/price-compare': typeof ApiPriceCompareRoute
  '/api/suggest-purpose': typeof ApiSuggestPurposeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/d/$shareUuid': typeof DShareUuidRoute
  '/d/test': typeof DTestRoute
  '/admin/campaigns': typeof AdminAdminCampaignsRoute
  '/admin/defamation': typeof AdminAdminDefamationRoute
  '/admin/extract': typeof AdminAdminExtractRoute
  '/admin/rules': typeof AdminAdminRulesRoute
  '/admin/sources': typeof AdminAdminSourcesRoute
  '/admin/trends': typeof AdminAdminTrendsRoute
  '/partner/billing': typeof PartnerPartnerBillingRoute
  '/partner/calendar': typeof PartnerPartnerCalendarRouteWithChildren
  '/partner/campaigns': typeof PartnerPartnerCampaignsRoute
  '/partner/coupons': typeof PartnerPartnerCouponsRoute
  '/partner/redeem': typeof PartnerPartnerRedeemRoute
  '/partner/register': typeof PartnerPartnerRegisterRoute
  '/partner/results': typeof PartnerPartnerResultsRoute
  '/coupon/$claim_code': typeof UserCouponClaim_codeRoute
  '/results/$shareUuid': typeof UserResultsShareUuidRoute
  '/api/coupons/claim': typeof ApiCouponsClaimRoute
  '/api/drops/$shareCode': typeof ApiDropsShareCodeRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/partner/': typeof PartnerPartnerIndexRoute
  '/api/discover/': typeof ApiDiscoverIndexRoute
  '/api/drops/': typeof ApiDropsIndexRoute
  '/partner/calendar/$dropId': typeof PartnerPartnerCalendarDropIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/create': typeof UserCreateRoute
  '/create-wizard': typeof UserCreateWizardRoute
  '/explore': typeof UserExploreRoute
  '/home': typeof UserHomeRoute
  '/inbox': typeof UserInboxRoute
  '/me': typeof UserMeRoute
  '/profile': typeof UserProfileRoute
  '/api/abuse-reports': typeof ApiAbuseReportsRoute
  '/api/consultations': typeof ApiConsultationsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/oembed': typeof ApiOembedRoute
  '/api/price-compare': typeof ApiPriceCompareRoute
  '/api/suggest-purpose': typeof ApiSuggestPurposeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/d/$shareUuid': typeof DShareUuidRoute
  '/d/test': typeof DTestRoute
  '/admin/campaigns': typeof AdminAdminCampaignsRoute
  '/admin/defamation': typeof AdminAdminDefamationRoute
  '/admin/extract': typeof AdminAdminExtractRoute
  '/admin/rules': typeof AdminAdminRulesRoute
  '/admin/sources': typeof AdminAdminSourcesRoute
  '/admin/trends': typeof AdminAdminTrendsRoute
  '/partner/billing': typeof PartnerPartnerBillingRoute
  '/partner/calendar': typeof PartnerPartnerCalendarRouteWithChildren
  '/partner/campaigns': typeof PartnerPartnerCampaignsRoute
  '/partner/coupons': typeof PartnerPartnerCouponsRoute
  '/partner/redeem': typeof PartnerPartnerRedeemRoute
  '/partner/register': typeof PartnerPartnerRegisterRoute
  '/partner/results': typeof PartnerPartnerResultsRoute
  '/coupon/$claim_code': typeof UserCouponClaim_codeRoute
  '/results/$shareUuid': typeof UserResultsShareUuidRoute
  '/api/coupons/claim': typeof ApiCouponsClaimRoute
  '/api/drops/$shareCode': typeof ApiDropsShareCodeRoute
  '/admin': typeof AdminAdminIndexRoute
  '/partner': typeof PartnerPartnerIndexRoute
  '/api/discover': typeof ApiDiscoverIndexRoute
  '/api/drops': typeof ApiDropsIndexRoute
  '/partner/calendar/$dropId': typeof PartnerPartnerCalendarDropIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_partner': typeof PartnerRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/_user/create': typeof UserCreateRoute
  '/_user/create-wizard': typeof UserCreateWizardRoute
  '/_user/explore': typeof UserExploreRoute
  '/_user/home': typeof UserHomeRoute
  '/_user/inbox': typeof UserInboxRoute
  '/_user/me': typeof UserMeRoute
  '/_user/profile': typeof UserProfileRoute
  '/api/abuse-reports': typeof ApiAbuseReportsRoute
  '/api/consultations': typeof ApiConsultationsRoute
  '/api/events': typeof ApiEventsRoute
  '/api/oembed': typeof ApiOembedRoute
  '/api/price-compare': typeof ApiPriceCompareRoute
  '/api/suggest-purpose': typeof ApiSuggestPurposeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/d/$shareUuid': typeof DShareUuidRoute
  '/d/test': typeof DTestRoute
  '/_admin/admin/campaigns': typeof AdminAdminCampaignsRoute
  '/_admin/admin/defamation': typeof AdminAdminDefamationRoute
  '/_admin/admin/extract': typeof AdminAdminExtractRoute
  '/_admin/admin/rules': typeof AdminAdminRulesRoute
  '/_admin/admin/sources': typeof AdminAdminSourcesRoute
  '/_admin/admin/trends': typeof AdminAdminTrendsRoute
  '/_partner/partner/billing': typeof PartnerPartnerBillingRoute
  '/_partner/partner/calendar': typeof PartnerPartnerCalendarRouteWithChildren
  '/_partner/partner/campaigns': typeof PartnerPartnerCampaignsRoute
  '/_partner/partner/coupons': typeof PartnerPartnerCouponsRoute
  '/_partner/partner/redeem': typeof PartnerPartnerRedeemRoute
  '/_partner/partner/register': typeof PartnerPartnerRegisterRoute
  '/_partner/partner/results': typeof PartnerPartnerResultsRoute
  '/_user/coupon/$claim_code': typeof UserCouponClaim_codeRoute
  '/_user/results/$shareUuid': typeof UserResultsShareUuidRoute
  '/api/coupons/claim': typeof ApiCouponsClaimRoute
  '/api/drops/$shareCode': typeof ApiDropsShareCodeRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_partner/partner/': typeof PartnerPartnerIndexRoute
  '/api/discover/': typeof ApiDiscoverIndexRoute
  '/api/drops/': typeof ApiDropsIndexRoute
  '/_partner/partner/calendar/$dropId': typeof PartnerPartnerCalendarDropIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/terms'
    | '/create'
    | '/create-wizard'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/me'
    | '/profile'
    | '/api/abuse-reports'
    | '/api/consultations'
    | '/api/events'
    | '/api/oembed'
    | '/api/price-compare'
    | '/api/suggest-purpose'
    | '/auth/callback'
    | '/d/$shareUuid'
    | '/d/test'
    | '/admin/campaigns'
    | '/admin/defamation'
    | '/admin/extract'
    | '/admin/rules'
    | '/admin/sources'
    | '/admin/trends'
    | '/partner/billing'
    | '/partner/calendar'
    | '/partner/campaigns'
    | '/partner/coupons'
    | '/partner/redeem'
    | '/partner/register'
    | '/partner/results'
    | '/coupon/$claim_code'
    | '/results/$shareUuid'
    | '/api/coupons/claim'
    | '/api/drops/$shareCode'
    | '/admin/'
    | '/partner/'
    | '/api/discover/'
    | '/api/drops/'
    | '/partner/calendar/$dropId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/terms'
    | '/create'
    | '/create-wizard'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/me'
    | '/profile'
    | '/api/abuse-reports'
    | '/api/consultations'
    | '/api/events'
    | '/api/oembed'
    | '/api/price-compare'
    | '/api/suggest-purpose'
    | '/auth/callback'
    | '/d/$shareUuid'
    | '/d/test'
    | '/admin/campaigns'
    | '/admin/defamation'
    | '/admin/extract'
    | '/admin/rules'
    | '/admin/sources'
    | '/admin/trends'
    | '/partner/billing'
    | '/partner/calendar'
    | '/partner/campaigns'
    | '/partner/coupons'
    | '/partner/redeem'
    | '/partner/register'
    | '/partner/results'
    | '/coupon/$claim_code'
    | '/results/$shareUuid'
    | '/api/coupons/claim'
    | '/api/drops/$shareCode'
    | '/admin'
    | '/partner'
    | '/api/discover'
    | '/api/drops'
    | '/partner/calendar/$dropId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_partner'
    | '/_user'
    | '/login'
    | '/terms'
    | '/_user/create'
    | '/_user/create-wizard'
    | '/_user/explore'
    | '/_user/home'
    | '/_user/inbox'
    | '/_user/me'
    | '/_user/profile'
    | '/api/abuse-reports'
    | '/api/consultations'
    | '/api/events'
    | '/api/oembed'
    | '/api/price-compare'
    | '/api/suggest-purpose'
    | '/auth/callback'
    | '/d/$shareUuid'
    | '/d/test'
    | '/_admin/admin/campaigns'
    | '/_admin/admin/defamation'
    | '/_admin/admin/extract'
    | '/_admin/admin/rules'
    | '/_admin/admin/sources'
    | '/_admin/admin/trends'
    | '/_partner/partner/billing'
    | '/_partner/partner/calendar'
    | '/_partner/partner/campaigns'
    | '/_partner/partner/coupons'
    | '/_partner/partner/redeem'
    | '/_partner/partner/register'
    | '/_partner/partner/results'
    | '/_user/coupon/$claim_code'
    | '/_user/results/$shareUuid'
    | '/api/coupons/claim'
    | '/api/drops/$shareCode'
    | '/_admin/admin/'
    | '/_partner/partner/'
    | '/api/discover/'
    | '/api/drops/'
    | '/_partner/partner/calendar/$dropId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PartnerRoute: typeof PartnerRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  LoginRoute: typeof LoginRoute
  TermsRoute: typeof TermsRoute
  ApiAbuseReportsRoute: typeof ApiAbuseReportsRoute
  ApiConsultationsRoute: typeof ApiConsultationsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiOembedRoute: typeof ApiOembedRoute
  ApiPriceCompareRoute: typeof ApiPriceCompareRoute
  ApiSuggestPurposeRoute: typeof ApiSuggestPurposeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DShareUuidRoute: typeof DShareUuidRoute
  DTestRoute: typeof DTestRoute
  ApiCouponsClaimRoute: typeof ApiCouponsClaimRoute
  ApiDropsShareCodeRoute: typeof ApiDropsShareCodeRoute
  ApiDiscoverIndexRoute: typeof ApiDiscoverIndexRoute
  ApiDropsIndexRoute: typeof ApiDropsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_partner': {
      id: '/_partner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/test': {
      id: '/d/test'
      path: '/d/test'
      fullPath: '/d/test'
      preLoaderRoute: typeof DTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$shareUuid': {
      id: '/d/$shareUuid'
      path: '/d/$shareUuid'
      fullPath: '/d/$shareUuid'
      preLoaderRoute: typeof DShareUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-purpose': {
      id: '/api/suggest-purpose'
      path: '/api/suggest-purpose'
      fullPath: '/api/suggest-purpose'
      preLoaderRoute: typeof ApiSuggestPurposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/price-compare': {
      id: '/api/price-compare'
      path: '/api/price-compare'
      fullPath: '/api/price-compare'
      preLoaderRoute: typeof ApiPriceCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oembed': {
      id: '/api/oembed'
      path: '/api/oembed'
      fullPath: '/api/oembed'
      preLoaderRoute: typeof ApiOembedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consultations': {
      id: '/api/consultations'
      path: '/api/consultations'
      fullPath: '/api/consultations'
      preLoaderRoute: typeof ApiConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/abuse-reports': {
      id: '/api/abuse-reports'
      path: '/api/abuse-reports'
      fullPath: '/api/abuse-reports'
      preLoaderRoute: typeof ApiAbuseReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/me': {
      id: '/_user/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof UserMeRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/inbox': {
      id: '/_user/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof UserInboxRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/home': {
      id: '/_user/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof UserHomeRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/explore': {
      id: '/_user/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof UserExploreRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/create-wizard': {
      id: '/_user/create-wizard'
      path: '/create-wizard'
      fullPath: '/create-wizard'
      preLoaderRoute: typeof UserCreateWizardRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/create': {
      id: '/_user/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof UserCreateRouteImport
      parentRoute: typeof UserRoute
    }
    '/api/drops/': {
      id: '/api/drops/'
      path: '/api/drops'
      fullPath: '/api/drops/'
      preLoaderRoute: typeof ApiDropsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover/': {
      id: '/api/discover/'
      path: '/api/discover'
      fullPath: '/api/discover/'
      preLoaderRoute: typeof ApiDiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_partner/partner/': {
      id: '/_partner/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerPartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/drops/$shareCode': {
      id: '/api/drops/$shareCode'
      path: '/api/drops/$shareCode'
      fullPath: '/api/drops/$shareCode'
      preLoaderRoute: typeof ApiDropsShareCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coupons/claim': {
      id: '/api/coupons/claim'
      path: '/api/coupons/claim'
      fullPath: '/api/coupons/claim'
      preLoaderRoute: typeof ApiCouponsClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/results/$shareUuid': {
      id: '/_user/results/$shareUuid'
      path: '/results/$shareUuid'
      fullPath: '/results/$shareUuid'
      preLoaderRoute: typeof UserResultsShareUuidRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/coupon/$claim_code': {
      id: '/_user/coupon/$claim_code'
      path: '/coupon/$claim_code'
      fullPath: '/coupon/$claim_code'
      preLoaderRoute: typeof UserCouponClaim_codeRouteImport
      parentRoute: typeof UserRoute
    }
    '/_partner/partner/results': {
      id: '/_partner/partner/results'
      path: '/partner/results'
      fullPath: '/partner/results'
      preLoaderRoute: typeof PartnerPartnerResultsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_partner/partner/register': {
      id: '/_partner/partner/register'
      path: '/partner/register'
      fullPath: '/partner/register'
      preLoaderRoute: typeof PartnerPartnerRegisterRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_partner/partner/redeem': {
      id: '/_partner/partner/redeem'
      path: '/partner/redeem'
      fullPath: '/partner/redeem'
      preLoaderRoute: typeof PartnerPartnerRedeemRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_partner/partner/coupons': {
      id: '/_partner/partner/coupons'
      path: '/partner/coupons'
      fullPath: '/partner/coupons'
      preLoaderRoute: typeof PartnerPartnerCouponsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_partner/partner/campaigns': {
      id: '/_partner/partner/campaigns'
      path: '/partner/campaigns'
      fullPath: '/partner/campaigns'
      preLoaderRoute: typeof PartnerPartnerCampaignsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_partner/partner/calendar': {
      id: '/_partner/partner/calendar'
      path: '/partner/calendar'
      fullPath: '/partner/calendar'
      preLoaderRoute: typeof PartnerPartnerCalendarRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_partner/partner/billing': {
      id: '/_partner/partner/billing'
      path: '/partner/billing'
      fullPath: '/partner/billing'
      preLoaderRoute: typeof PartnerPartnerBillingRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_admin/admin/trends': {
      id: '/_admin/admin/trends'
      path: '/admin/trends'
      fullPath: '/admin/trends'
      preLoaderRoute: typeof AdminAdminTrendsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/sources': {
      id: '/_admin/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminAdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/rules': {
      id: '/_admin/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminAdminRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/extract': {
      id: '/_admin/admin/extract'
      path: '/admin/extract'
      fullPath: '/admin/extract'
      preLoaderRoute: typeof AdminAdminExtractRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/defamation': {
      id: '/_admin/admin/defamation'
      path: '/admin/defamation'
      fullPath: '/admin/defamation'
      preLoaderRoute: typeof AdminAdminDefamationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/campaigns': {
      id: '/_admin/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminAdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_partner/partner/calendar/$dropId': {
      id: '/_partner/partner/calendar/$dropId'
      path: '/$dropId'
      fullPath: '/partner/calendar/$dropId'
      preLoaderRoute: typeof PartnerPartnerCalendarDropIdRouteImport
      parentRoute: typeof PartnerPartnerCalendarRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCampaignsRoute: typeof AdminAdminCampaignsRoute
  AdminAdminDefamationRoute: typeof AdminAdminDefamationRoute
  AdminAdminExtractRoute: typeof AdminAdminExtractRoute
  AdminAdminRulesRoute: typeof AdminAdminRulesRoute
  AdminAdminSourcesRoute: typeof AdminAdminSourcesRoute
  AdminAdminTrendsRoute: typeof AdminAdminTrendsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCampaignsRoute: AdminAdminCampaignsRoute,
  AdminAdminDefamationRoute: AdminAdminDefamationRoute,
  AdminAdminExtractRoute: AdminAdminExtractRoute,
  AdminAdminRulesRoute: AdminAdminRulesRoute,
  AdminAdminSourcesRoute: AdminAdminSourcesRoute,
  AdminAdminTrendsRoute: AdminAdminTrendsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PartnerPartnerCalendarRouteChildren {
  PartnerPartnerCalendarDropIdRoute: typeof PartnerPartnerCalendarDropIdRoute
}

const PartnerPartnerCalendarRouteChildren: PartnerPartnerCalendarRouteChildren =
  {
    PartnerPartnerCalendarDropIdRoute: PartnerPartnerCalendarDropIdRoute,
  }

const PartnerPartnerCalendarRouteWithChildren =
  PartnerPartnerCalendarRoute._addFileChildren(
    PartnerPartnerCalendarRouteChildren,
  )

interface PartnerRouteChildren {
  PartnerPartnerBillingRoute: typeof PartnerPartnerBillingRoute
  PartnerPartnerCalendarRoute: typeof PartnerPartnerCalendarRouteWithChildren
  PartnerPartnerCampaignsRoute: typeof PartnerPartnerCampaignsRoute
  PartnerPartnerCouponsRoute: typeof PartnerPartnerCouponsRoute
  PartnerPartnerRedeemRoute: typeof PartnerPartnerRedeemRoute
  PartnerPartnerRegisterRoute: typeof PartnerPartnerRegisterRoute
  PartnerPartnerResultsRoute: typeof PartnerPartnerResultsRoute
  PartnerPartnerIndexRoute: typeof PartnerPartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerPartnerBillingRoute: PartnerPartnerBillingRoute,
  PartnerPartnerCalendarRoute: PartnerPartnerCalendarRouteWithChildren,
  PartnerPartnerCampaignsRoute: PartnerPartnerCampaignsRoute,
  PartnerPartnerCouponsRoute: PartnerPartnerCouponsRoute,
  PartnerPartnerRedeemRoute: PartnerPartnerRedeemRoute,
  PartnerPartnerRegisterRoute: PartnerPartnerRegisterRoute,
  PartnerPartnerResultsRoute: PartnerPartnerResultsRoute,
  PartnerPartnerIndexRoute: PartnerPartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface UserRouteChildren {
  UserCreateRoute: typeof UserCreateRoute
  UserCreateWizardRoute: typeof UserCreateWizardRoute
  UserExploreRoute: typeof UserExploreRoute
  UserHomeRoute: typeof UserHomeRoute
  UserInboxRoute: typeof UserInboxRoute
  UserMeRoute: typeof UserMeRoute
  UserProfileRoute: typeof UserProfileRoute
  UserCouponClaim_codeRoute: typeof UserCouponClaim_codeRoute
  UserResultsShareUuidRoute: typeof UserResultsShareUuidRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserCreateRoute: UserCreateRoute,
  UserCreateWizardRoute: UserCreateWizardRoute,
  UserExploreRoute: UserExploreRoute,
  UserHomeRoute: UserHomeRoute,
  UserInboxRoute: UserInboxRoute,
  UserMeRoute: UserMeRoute,
  UserProfileRoute: UserProfileRoute,
  UserCouponClaim_codeRoute: UserCouponClaim_codeRoute,
  UserResultsShareUuidRoute: UserResultsShareUuidRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PartnerRoute: PartnerRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  LoginRoute: LoginRoute,
  TermsRoute: TermsRoute,
  ApiAbuseReportsRoute: ApiAbuseReportsRoute,
  ApiConsultationsRoute: ApiConsultationsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiOembedRoute: ApiOembedRoute,
  ApiPriceCompareRoute: ApiPriceCompareRoute,
  ApiSuggestPurposeRoute: ApiSuggestPurposeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DShareUuidRoute: DShareUuidRoute,
  DTestRoute: DTestRoute,
  ApiCouponsClaimRoute: ApiCouponsClaimRoute,
  ApiDropsShareCodeRoute: ApiDropsShareCodeRoute,
  ApiDiscoverIndexRoute: ApiDiscoverIndexRoute,
  ApiDropsIndexRoute: ApiDropsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
